### PR TITLE
Update helmenv.sh

### LINKED ISSUE #14: Doesn't work for newer versions of helm
Helm is now hosting in https://get.helm.sh/ instead of https://storage.googleapis.com/kubernetes-helm/
The script should get the url from the API instead of assuming one.

### PR DESCRIPTION
**Pull request by luisdavim**
This should fix #14

### CODE REVIEW

**Comment by alexppg** [comment]
I'm not sure I get it. Does the quotation mark make a difference? Did it stop working? I've been using it and I didn't have a problem @luisdavim

**Comment by luisdavim** [comment]
Yes, maybe it's a zsh vs bash thing but without the quotes it tries to download from the old location.

**Comment by alexppg** [comment]
Ok then. It won't be bad, for sure.

**Comment by alexppg** [comment]
Ok then. It won't be bad, for sure.

**Pull request merged**
